---
- block:
    - name: Allow rhsm a longer timeout to help out with subscription-manager
      lineinfile:
        dest: /etc/rhsm/rhsm.conf
        line: 'server_timeout=600'
        insertafter: '^proxy_password ='

    - name: Check for sat config file
      stat: path=/etc/rhsm/rhsm.conf.kat-backup
      register: sat_cfg

    - name: Remove satellite configuration if using RH CDN
      command: "mv -f /etc/rhsm/rhsm.conf.kat-backup /etc/rhsm/rhsm.conf"
      when: rhnusername is defined and rhnusername and sat_cfg.stat.exists == True
      ignore_errors: yes

    - name: Remove satellite SSL if using RH CDN
      command: "rpm -e $(rpm -qa katello-ca-consumer*)"
      when: rhnusername is defined and rhnusername and sat_cfg.stat.exists == True
      ignore_errors: yes

    - name: Is the host already registered?
      command: "subscription-manager version"
      register: subscribed
      changed_when: no
      ignore_errors: yes

    - name: Install Katello RPM if set
      yum:
        name: "{{ rhsm_katello_url }}"
        state: present
      when: rhsm_katello_url is defined and rhsm_katello_url

    - name: Register host via Activation key
      redhat_subscription:
        activationkey: "{{ rhnusername }}"
        org_id: "{{ rhnpassword }}"
        state: present
        pool: "{{ subscriptionpoolid }}"
      when: rhsmusernamepasswordoractivationkey is defined and rhsmusernamepasswordoractivationkey == 'activationkey'
      register: register_key_result
      ignore_errors: yes

    - name: Register host
      redhat_subscription:
        username: "{{ rhnusername }}"
        password: "{{ rhnpassword }}"
        server_hostname: "{{ rhsm_server }}"
        state: present
        pool: "{{ subscriptionpoolid }}"
      #when: "('not registered' in subscribed.stdout or 'Current' not in subscribed.stdout) and rhnusername is defined and rhnusername"
      when: "'not registered' in subscribed.stdout and rhnusername is defined and rhnusername"

    - name: Check if subscription is attached
      command: subscription-manager list --consumed --pool-only # JTH: Broken --matches="{{ subscriptionpoolid }}"
      register: subscription_attached
      when: subscriptionpoolid is defined and subscriptionpoolid
      changed_when: no

    - block:
        - name: Get pool id
          shell: "subscription-manager list --available --pool-only |grep {{ subscriptionpoolid }}" # --matches="{{ subscriptionpoolid }}" | head -n 1
          register: pool_id
          changed_when: no

        - name: Fail if no pool ID is returned
          fail:
            msg: No subscription matching "{{ subscriptionpoolid }}" found
          when:  subscriptionpoolid not in pool_id.stdout

        - name: Attach subscription
          command: subscription-manager attach --pool="{{ pool_id.stdout }}"

      #when: subscriptionpoolid is defined and subscriptionpoolid and not skip_packages is defined
      when:
        - subscriptionpoolid is defined
        - subscriptionpoolid not in subscription_attached.stdout

    - name: Install katello-agent RPM if we are using satellite
      yum:
        name: katello-agent
        state: present
      when: rhsm_katello_url is defined and rhsm_katello_url
  
  when: ansible_distribution == "RedHat"
